#
# Samantha Foley
# CS 441/541: Project 4 Given Tests
#

check: scheduler banner_help \
	check-python

banner_help:
	@echo "By default check will run all levels."
	@echo "   check-level-1"
	@echo "   check-level-2"
	@echo "   check-level-3"
	@echo "   check-level-4"
	@echo "   check-level-5"
	@echo "   check-level-6"
	@echo "   check-level-7"
	@echo ""
	@sleep 1

check-python:
	@python given-tests/tester-list.py  given-tests/test-list-scheduler
